### ISSUE TITLE
Stairs on hands are so HUGE

### ISSUE THREAD

**Issue by shoyguer** [vini2003/Bamboo-Tweaks#1]
When you're with the bamboo stairs on your hands, it's very very big.
Take any stairs on your hands and after the bamboo stairs, you'll understand...
Thank you for your awesome mod!

**Comment by vini2003** [comment]
solved!

**Comment by TrueCP6** [comment]
Problem is present in 1.16 as well as the item being huge when dropped on the ground
![](https://user-images.githubusercontent.com/39642832/87218702-57268480-c355-11ea-9585-3a5409d80de4.png)
![](https://user-images.githubusercontent.com/39642832/87218704-5c83cf00-c355-11ea-94ed-23e35b626735.png)
