### ISSUE TITLE
Missing blocks.

### ISSUE THREAD

**Issue by K0-RR** [vini2003/Bamboo-Tweaks#10]
There is no:
- trapdoor
- slab

**Comment by K0-RR** [comment]
A little misspelling 
![image](https://user-images.githubusercontent.com/43277609/114297696-70aa5780-9ab2-11eb-8154-f86651be9ef9.png)

**Comment by vini2003** [comment]
Good ideas. I'll get around to them - fixed the misspelling as well, thanks!

**Comment by vini2003** [comment]
Added in release `3.0.0`.
