### ISSUE TITLE
Bamboo blocks cannot be used as fuel in the smoker.

### ISSUE THREAD

**Issue by Greg-J** [vini2003/Bamboo-Tweaks#16]
I don't know if they can be used in the furnace or blast furnace as I haven't tried, but I can confirm that they can't be used as fuel in the smoker which seems like an oversight.

**Comment by vini2003** [comment]
Oh, I forgot to re-add the `FuelRegistry` stuff - thanks for reporting.

**Comment by Greg-J** [comment]
Any chances it'll get an update soon?

**Comment by vini2003** [comment]
Fixed in release `3.0.0`.
