### ISSUE TITLE
Item give back after breaking

### ISSUE THREAD

**Issue by AlexisBloodwood** [vini2003/Bamboo-Tweaks#7]
I'm using version 2.0.0-1.16.1 on my 1.16.3 Fabric server and some of the items when broken either duplicate or don't drop their item when mined. I have yet to test this on all of them but have confirmed this on the Door and the Fence Wall.

I'm breaking them using a Fortune 3, Unbreaking 3, Efficiency 5, Mending, Netherite Axe if that helps.

**Comment by K0-RR** [comment]
Seems to be fixed.

**Comment by vini2003** [comment]
Indeed, fixed.
